name: hello_farmer
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Updated Firebase versions for compatibility
  firebase_core: ^2.32.0 
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  
  provider: ^6.1.1
  permission_handler: ^11.0.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  maps_toolkit: ^3.0.0
  geocoding: ^2.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
